### ISSUE TITLE
Support Chang hardfork

### ISSUE THREAD

**Issue by rmgaray** [mlabs-haskell/godot-cardano#89]
We are getting `EraMismatch` errors in our demos, probably due to CSL not supporting the Conway features yet.

**Comment by rmgaray** [comment]
I'm updating the description here:

The version to this date is `11.5.0`, which is incompatible with the Conway update. We would like to update to version `14.1.X`, which should allow us to re-gain compatibility with mainnet. I tried to compile with version `14.1.1` and noticed *many* compilation errors due to modules becoming private (to name a few: `CSL::{crypto, error, plutus, tx_builder, utils}`). I'm afraid this update might be onerous.
